services:

    Code4Nix\UriSigner\UriSigner:
        public: false
        arguments:
            - '%kernel.secret%'
            - '%code4nix_uri_signer.parameter%'
            - '%code4nix_uri_signer.expiration%'

    code4nix_uri_signer.uri_signer:
        alias: Code4Nix\UriSigner\UriSigner
        public: true
